###############################################################
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: "Veracode"

on:
  #  push:
  #    branches: [main]
  # pull_request:
  # The branches below must be a subset of the branches above
  # branches: [ main ]
  # paths-ignore:
  #   - "**/*.md"
  #   - "**/*.txt"
  # Trigger manually
  workflow_dispatch:
  # Triggered once a week
  schedule:
   - cron: "0 0 * * 0"


env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  analyze-ssi-authority-schema-registry-service:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/hub/SsiAuthoritySchemaRegistry.Service

      - name: Build and publish
        run: |
          cd src/hub/SsiAuthoritySchemaRegistry.Service
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r ssi-authority-schema-registry-service.zip
          src/hub/SsiAuthoritySchemaRegistry.Service/.publish
          -x
          src/hub/SsiAuthoritySchemaRegistry.Service/.publish/Org.Eclipse.TractusX.SsiAuthoritySchemaRegistry.Service

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "ssi-authority-schema-registry-Service"
          createprofile: true
          teams: 'ssi-authority-schema-registry'
          # Specify path to upload
          filepath: "ssi-authority-schema-registry-service.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.SsiAuthoritySchemaRegistry.Service.dll'

  analyze-ssi-authority-schema-registry-migrations:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore src/database/SsiAuthoritySchemaRegistry.Migrations

      - name: Build and publish
        run: |
          cd src/database/SsiAuthoritySchemaRegistry.Migrations
          dotnet build --no-restore
          dotnet publish -c Debug  -p:PublishDir=.\publish

      - name: "Bundle files to scan"
        run: >
          zip -r ssi-authority-schema-registry-migrations.zip
          src/database/SsiAuthoritySchemaRegistry.Migrations/.publish

      - name: Run Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # Specify Veracode application name
          appname: "ssi-authority-schema-registry-Migrations"
          createprofile: true
          teams: 'ssi-authority-schema-registry'
          # Specify path to upload
          filepath: "ssi-authority-schema-registry-migrations.zip"
          vid: "${{ secrets.ORG_VERACODE_API_ID }}"
          vkey: "${{ secrets.ORG_VERACODE_API_KEY }}"
          include: 'Org.Eclipse.TractusX.SsiAuthoritySchemaRegistry.Migrations.dll'
